#!/bin/sh
#AccuWeather (r) RSS weather tool for conky
#
#USAGE: weather.sh UKXX0062
#
#(c) Michael Seiler 2007
METRIC=1 #Should be 0 or 1; 0 for F, 1 for C
curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=KINT | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }'

case $BLOCK_BUTTON in
    3) pkill -RTMIN+4 i3blocks
        ;;
    *) ;;
esac
